function interactive_complex_exponential()
    % 创建图形窗口
    fig = figure('Name', '交互式复数指数函数 e^s', ...
        'NumberTitle', 'off', ...
        'Position', [100, 100, 800, 600]);

    % 初始化 s 的实部和虚部
    initial_real = 0;
    initial_imag = 0;
    s = initial_real + 1i * initial_imag;
    E = exp(s);

    % 创建坐标轴用于绘制 e^s
    ax = axes('Parent', fig, ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.2, 0.65, 0.75]);
    grid on;
    axis equal;
    xlim([-20, 20]);
    ylim([-20, 20]);
    xlabel('实部');
    ylabel('虚部');
    title('e^{s} 在复平面中的位置');
    hold on;

    % 绘制 e^s 的初始位置
    hPoint = plot(ax, real(E), imag(E), 'ro', 'MarkerSize', 10, 'MarkerFaceColor', 'r');
    % 绘制原点
    plot(ax, 0, 0, 'k+', 'MarkerSize', 10, 'LineWidth', 2);

    % 显示 e^s 的模和相位
    txt_mod = annotation('textbox', [0.05, 0.7, 0.2, 0.1], ...
        'String', sprintf('|e^{s}| = %.2f', abs(E)), ...
        'FitBoxToText', 'on', ...
        'FontSize', 12, ...
        'BackgroundColor', 'white');
    txt_phase = annotation('textbox', [0.05, 0.6, 0.2, 0.1], ...
        'String', sprintf('arg(e^{s}) = %.2f rad', angle(E)), ...
        'FitBoxToText', 'on', ...
        'FontSize', 12, ...
        'BackgroundColor', 'white');

    % 创建滑动条用于调整 s 的实部
    uicontrol('Parent', fig, ...
        'Style', 'slider', ...
        'Min', -5, 'Max', 5, ...
        'Value', initial_real, ...
        'Units', 'normalized', ...
        'Position', [0.1, 0.1, 0.6, 0.05], ...
        'Tag', 'realSlider', ...
        'Callback', @updatePlot);
    % 添加实部标签
    uicontrol('Parent', fig, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.1, 0.16, 0.6, 0.03], ...
        'String', '调整 s 的实部', ...
        'FontSize', 12);

    % 创建滑动条用于调整 s 的虚部
    uicontrol('Parent', fig, ...
        'Style', 'slider', ...
        'Min', -5, 'Max', 5, ...
        'Value', initial_imag, ...
        'Units', 'normalized', ...
        'Position', [0.1, 0.05, 0.6, 0.05], ...
        'Tag', 'imagSlider', ...
        'Callback', @updatePlot);
    % 添加虚部标签
    uicontrol('Parent', fig, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.1, 0.11, 0.6, 0.03], ...
        'String', '调整 s 的虚部', ...
        'FontSize', 12);

    % 回调函数，用于更新图形
    function updatePlot(src, ~)
        % 获取滑动条的值
        real_val = findobj(fig, 'Tag', 'realSlider').Value;
        imag_val = findobj(fig, 'Tag', 'imagSlider').Value;
        s_new = real_val + 1i * imag_val;
        E_new = exp(s_new);

        % 更新 e^s 的位置
        set(hPoint, 'XData', real(E_new), 'YData', imag(E_new));

        % 更新模和相位显示
        set(txt_mod, 'String', sprintf('|e^{s}| = %.2f', abs(E_new)));
        set(txt_phase, 'String', sprintf('arg(e^{s}) = %.2f rad', angle(E_new)));

        % 更新图形标题显示当前 s
        title(ax, sprintf('e^{s} 在复平面中的位置\ns = %.2f + %.2fi', real_val, imag_val));
    end

end
